services:
  nginx:
    image: spokerv2-nginx-dev
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3201:80"
    depends_on:
      - frontend
      - backend

  frontend:
    image: spokerv2-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "4200"
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package.json

  backend:
    image: spokerv2-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    expose:
      - "5001"
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/package.json
