const { readdirSync, readFileSync, mkdirSync, writeFileSync, unlinkSync } = require('fs');
const { execSync } = require('child_process');
const path = require('path');
const os = require('os');

// --- CLI arg parsing (simple) -------------------------------------------
const argv = require('process').argv.slice(2);
function getArg(name, short) {
  const longIdx = argv.indexOf(`--${name}`);
  const shortIdx = short ? argv.indexOf(`-${short}`) : -1;
  const idx = longIdx !== -1 ? longIdx : shortIdx;
  if (idx !== -1 && argv.length > idx + 1) return argv[idx + 1];
  return null;
}

const docsDir = path.resolve(getArg('docs', 'd') || path.join(__dirname, '../../backend/docs'));
const backendOutDir = path.resolve(getArg('backend-out', 'b') || path.join(__dirname, '../../backend/src/swagger'));
const frontendOutDir = path.resolve(getArg('frontend-out', 'f') || path.join(__dirname, '../../frontend/src/swagger'));
const apiVersion = getArg('version', 'v') || '1.0.0';
let apiTitle = getArg('title', 't');
if (!apiTitle) {
  try {
    const pkg = require(path.resolve(__dirname, '../../package.json'));
    if (!pkg.project) {
      console.error('WARNING: package.json.project not found; using package.json.name for API title');
      apiTitle = (pkg.name || 'Spoker v2') + ' API';
    } else {
      apiTitle = pkg.project + ' API';
    }
  } catch (e) {
    apiTitle = 'Spoker v2 API';
  }
}

if (argv.includes('-h') || argv.includes('--help')) {
  console.log(`Usage: node generate-types.js [options]\n\nOptions:\n  -d, --docs <path>          Path to OpenAPI YAML source directory (default: backend/docs)\n  -b, --backend-out <path>   Output directory for backend types (default: backend/src/swagger)\n  -f, --frontend-out <path>  Output directory for frontend types (default: frontend/src/swagger)\n  -t, --title <string>       API title for generated temp specs\n  -v, --version <string>     API version for generated temp specs\n  -h, --help                 Show this help message\n`);
  process.exit(0);
}

mkdirSync(backendOutDir, { recursive: true });
mkdirSync(frontendOutDir, { recursive: true });

const baseHeader = `openapi: 3.0.0
info:
  title: ${apiTitle}
  version: '${apiVersion}'
`;

const yamlFiles = readdirSync(docsDir).filter((f) => f.endsWith('.yaml'));

console.log('🔄 Generating TypeScript types from OpenAPI specs...\n');

// Generate individual type files
for (const file of yamlFiles) {
  const name = path.parse(file).name;
  console.log(`  ✓ Processing ${file}...`);
  
  const source = readFileSync(path.join(docsDir, file), 'utf8');
  const tempSpec = path.join(os.tmpdir(), `${name}-spec.yaml`);
  writeFileSync(tempSpec, baseHeader + '\n' + source);
  
  execSync(`npx openapi-typescript ${tempSpec} --output ${path.join(backendOutDir, name + '.ts')}`, { stdio: 'inherit' });
  execSync(`npx openapi-typescript ${tempSpec} --output ${path.join(frontendOutDir, name + '.ts')}`, { stdio: 'inherit' });
  
  unlinkSync(tempSpec);
}

console.log('\n📦 Generating unified API index...\n');

// Generate unified index for frontend
const frontendIndexContent = `/**
 * Auto-generated unified API types
 * Generated: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * To regenerate: Run 'npm run swagger:gen' from the repository root directory
 */

${yamlFiles.map(file => {
  const name = path.parse(file).name;
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  return `import type { paths as ${capitalizedName}Paths, components as ${capitalizedName}Components } from './${name}';`;
}).join('\n')}

// Unified paths type - combines all API endpoints
export type ApiPaths = ${yamlFiles.map(file => {
  const name = path.parse(file).name;
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  return `${capitalizedName}Paths`;
}).join(' & ')};

// Re-export all components
${yamlFiles.map(file => {
  const name = path.parse(file).name;
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  return `export type { ${capitalizedName}Components };`;
}).join('\n')}

// Convenience type exports
${yamlFiles.map(file => {
  const name = path.parse(file).name;
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  return `export type { paths as ${capitalizedName}Paths } from './${name}';`;
}).join('\n')}
`;

writeFileSync(path.join(frontendOutDir, 'index.ts'), frontendIndexContent);

console.log('  ✓ Created frontend/src/swagger/index.ts');
console.log('\n✨ Code generation complete!\n');
console.log('📋 Generated types for:');
yamlFiles.forEach(file => console.log(`   - ${file}`));
console.log('');