const { readdirSync, readFileSync, mkdirSync, writeFileSync, unlinkSync } = require('fs');
const { execSync } = require('child_process');
const path = require('path');
const os = require('os');

const docsDir = path.resolve(__dirname, '../backend/docs');
const backendOutDir = path.resolve(__dirname, '../backend/src/swagger');
const frontendOutDir = path.resolve(__dirname, '../frontend/src/swagger');

mkdirSync(backendOutDir, { recursive: true });
mkdirSync(frontendOutDir, { recursive: true });

const baseHeader = `openapi: 3.0.0
info:
  title: Spoker v2 API
  version: '1.0.0'
`;

const yamlFiles = readdirSync(docsDir).filter((f) => f.endsWith('.yaml'));

console.log('🔄 Generating TypeScript types from OpenAPI specs...\n');

// Generate individual type files
for (const file of yamlFiles) {
  const name = path.parse(file).name;
  console.log(`  ✓ Processing ${file}...`);
  
  const source = readFileSync(path.join(docsDir, file), 'utf8');
  const tempSpec = path.join(os.tmpdir(), `${name}-spec.yaml`);
  writeFileSync(tempSpec, baseHeader + '\n' + source);
  
  execSync(`npx openapi-typescript ${tempSpec} --output ${path.join(backendOutDir, name + '.ts')}`, { stdio: 'inherit' });
  execSync(`npx openapi-typescript ${tempSpec} --output ${path.join(frontendOutDir, name + '.ts')}`, { stdio: 'inherit' });
  
  unlinkSync(tempSpec);
}

console.log('\n📦 Generating unified API index...\n');

// Generate unified index for frontend
const frontendIndexContent = `/**
 * Auto-generated unified API types
 * Generated: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run from repo root: npm run swagger:gen
 */

${yamlFiles.map(file => {
  const name = path.parse(file).name;
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  return `import type { paths as ${capitalizedName}Paths, components as ${capitalizedName}Components } from './${name}';`;
}).join('\n')}

// Unified paths type - combines all API endpoints
export type ApiPaths = ${yamlFiles.map(file => {
  const name = path.parse(file).name;
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  return `${capitalizedName}Paths`;
}).join(' & ')};

// Re-export all components
${yamlFiles.map(file => {
  const name = path.parse(file).name;
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  return `export type { ${capitalizedName}Components };`;
}).join('\n')}

// Convenience type exports
${yamlFiles.map(file => {
  const name = path.parse(file).name;
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  return `export type { paths as ${capitalizedName}Paths } from './${name}';`;
}).join('\n')}
`;

writeFileSync(path.join(frontendOutDir, 'index.ts'), frontendIndexContent);

console.log('  ✓ Created frontend/src/swagger/index.ts');
console.log('\n✨ Code generation complete!\n');
console.log('📋 Generated types for:');
yamlFiles.forEach(file => console.log(`   - ${file}`));
console.log('');
