name: Spoker CI - Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test, and E2E
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t spoker-frontend ./frontend

      # Step 3: Run Karma unit tests inside Docker
      - name: Run Karma unit tests
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/frontend:/app \
          -w /app spoker-frontend \
          sh -c "npm run test -- --no-watch --no-progress"

      # Step 4: Upload coverage artifact
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage
          path: frontend/coverage/

      # Step 5: Run Cypress E2E tests inside Docker
      - name: Run Cypress E2E tests
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/frontend:/app \
          -w /app spoker-frontend \
          sh -c "npm run test:e2e"